### PR TITLE
[DEVOI-563] Documentation extension

### PR DESCRIPTION
**Pull request by JahnChoi-LR**
JIRA: https://liveramp.atlassian.net/browse/DEVOI-563

Changes:
- Adding `input_path` option for the kdt publish step to allow parallelization of multiple publishes via Jenkins.

Notes:
- Complementary [PR](https://github.com/LiveRamp/identity/pull/1939) for Online Identity Jenkins
- Parallelizing `publish` step

### CODE REVIEW

**Comment by JahnChoi-LR** [comment]
Feel free to reach out via Slack for a more extensive explanation of the changes proposed.

**Review by asaranglr — COMMENTED** [review]
Could you add some tests in the description to demonstrate this works ? A section describing how it works currently would be good too.
You can locally build the ruby gem to test it out.
Also, as a side note, consider moving to Helm charts instead of relying on additional features with KDT.

**Comment by asaranglr** [comment]
> Feel free to reach out via Slack for a more extensive explanation of the changes proposed.

Asking for it in the description so that it's captured in the description for future reference.

**Comment by ayush-lr** [comment]
yeah, we are working on adding a test case.

For,
> consider moving to Helm charts instead of relying on additional features with KDT

Our current Jenkins flow uses KDT, so trying to improve this flow instead.

**Review by ranesagar — APPROVED** [review]

**Pull request merged**
